package:
  name: cmake_example
  version: 0.1

build:
  number: 0.1
  script_env:
    - CC
    - CXX

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
    - pybind11
    - cmake

  run:
    - python
    - vs2015_runtime  # [win]

test:
  imports:
    - cmake_example

about:
  summary: An example project built with pybind11.
  license_file: LICENSE
